/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PlaybackCtrlService_constants.h"

namespace hawkeye {

const PlaybackCtrlServiceConstants g_PlaybackCtrlService_constants;

PlaybackCtrlServiceConstants::PlaybackCtrlServiceConstants() {
}

} // namespace

