/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AcquireStoreService_CONSTANTS_H
#define AcquireStoreService_CONSTANTS_H

#include "AcquireStoreService_types.h"

namespace hawkeye {

class AcquireStoreServiceConstants {
 public:
  AcquireStoreServiceConstants();

};

extern const AcquireStoreServiceConstants g_AcquireStoreService_constants;

} // namespace

#endif
