/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AgentServer_constants.h"

namespace hawkeye {

const AgentServerConstants g_AgentServer_constants;

AgentServerConstants::AgentServerConstants() {
}

} // namespace

