/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AgentServer_CONSTANTS_H
#define AgentServer_CONSTANTS_H

#include "AgentServer_types.h"

namespace hawkeye {

class AgentServerConstants {
 public:
  AgentServerConstants();

};

extern const AgentServerConstants g_AgentServer_constants;

} // namespace

#endif
