/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PlaybackCtrlService_CONSTANTS_H
#define PlaybackCtrlService_CONSTANTS_H

#include "PlaybackCtrlService_types.h"

namespace hawkeye {

class PlaybackCtrlServiceConstants {
 public:
  PlaybackCtrlServiceConstants();

};

extern const PlaybackCtrlServiceConstants g_PlaybackCtrlService_constants;

} // namespace

#endif
