/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AcquireStoreService_constants.h"

namespace hawkeye {

const AcquireStoreServiceConstants g_AcquireStoreService_constants;

AcquireStoreServiceConstants::AcquireStoreServiceConstants() {
}

} // namespace

